### ISSUE TITLE
How to get drr.mhd

### ISSUE THREAD

**Issue by sugartao** [ZywooSimple/RT-SRTS#1]

**Comment by ZywooSimple** [comment]
We use RTK software to find forward projection of mhd file. The link to the RTK software is given in our github project, and you can download the RTK software from the official website. Specifically, we use os.system(f'/home/zmx/RTK/rtksimulatedgeometry -f {str(first_angle)} -n 1 --arc {str(arc)} -o {geometry_filepath} && /home/ zmx/RTK/rtkforwardprojections -g {geometry_filepath} -i {rtkct_filepath} -o {drr_filepath} --dimension=128 --fp=CudaRayCast') to generate the DRR. you can refer to the RTK's official documentation or check the help file (-h) on the console for .exe to understand each parameter.

**Comment by sugartao** [comment]
OK, thank you for your reply

**Comment by malonzia** [comment]
I can't reproduce the process of generating 1080 training samples for each CT using PCA-MM. Could you tell me the complete implementation process.
